name: Package on Release
# Dummy change 

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create subdirectory
        run: mkdir TextExtendAI

      - name: Checkout repository into subdirectory
        uses: actions/checkout@v3
        with:
          path: TextExtendAI

      - name: Package plugin
        run: zip -r TextExtendAI.zip TextExtendAI -x "TextExtendAI/.*"

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: TextExtendAI.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
